### PR TITLE
Added Four Circles spinner

### PR DESCRIPTION
**Pull request by evgost**
Added a new spinner and added "spinners/11-folding-cube" to spinkit.scss.

### CODE REVIEW

**Comment by tobiasahlin** [comment]
@evgenyo :bow: thanks for this! There's a lot of diffs here that are just indentation changes, could you look at cleaning that up? :Heart:

**Comment by evgenyo** [comment]
@tobiasahlin I believe  https://github.com/tobiasahlin/SpinKit/commit/d45b25cf9f63c8c5fe7c1115ab2f921bc924319b commit never applied the "easier to copy" fix to the HTML/CSS examples, so it's not indentations but removed stars. And since 11-folding-cube was never added to spingkit.scss before, it's added in spinkit.css in this fork as well.

**Comment by tobiasahlin** [comment]
@evgenyo Sorry about that :bow: my fault! Would you mind updating from `master` now? Fixed this, so your PR should be all clean and tidy once you merge in :sparkles::ok_hand:

**Comment by evgenyo** [comment]
@tobiasahlin No worries! Should be all fixed up :)

**Comment by tobiasahlin** [comment]
@evgenyo Thanks! :pray: This is looking smooth… wondering though if it can become even smoother. The blinking (fading in/out) is throwing me off a bit, maybe it'd look better if all the circles were hidden/shown through moving and/or scaling? Thinking out loud here, sorry if I'm not making any sense, but I feel like the dots are behaving in two very different ways. Would be great to make their animation patterns more consistent :) relying only on translation and scale could be a way to achieve that.

**Comment by evgenyo** [comment]
@tobiasahlin Hello hello! I actually messed around with scale vs opacity, and personally preferred the blinking effect over shrinking because it gave me a loading vibe rather than just a pretty animation. Having said that, it's your project so you tell me what works with your vision best. I also changed the left/top/right/bottom movements to transform:translate as well. Let me know if there's anything else : )

**Pull request closed without merging**
