### PR TITLE
New bounce animation & gulpfile regex fix

### PR DESCRIPTION
**Pull request by chris--jones**
Added a new animation (sort of a variant of 7, but bouncing upward rather than growing/shrinking).
The gulpfile regex was not working as period (.) was not matching whitespace, so I have fixed this as well.

### CODE REVIEW

**Comment by jmagnusson** [comment]
Hmm I wonder why the regex stopped working. Perhaps it's some change in Node v4. Thanks for finding it @chris--jones, do you think you could submit that as a separate PR?

As for the animation I think @tobiasahlin will have to give his vote, considering he's the author, and CSS guru :smile:

**Comment by tobiasahlin** [comment]
@chris--jones Thanks for this! I'm :+1: on what @jmagnusson said here, could you separate these two changes in to two separate PRs? Regex fix is an instant merge, but will need to look closer on the animation :sparkles::pray:

**Comment by chris--jones** [comment]
Sure thing, but I've just recently left the country, so it'll be another week or so before I'm back at a computer.

**Comment by jmagnusson** [comment]
@chris--jones Thanks.

**Comment by tobiasahlin** [comment]
@chris--jones Thank you! Happy travels! :raised_hands:

**Pull request closed without merging**
